### ISSUE TITLE
Layout bug

### ISSUE THREAD

**Issue by quanpro198** [maquinas07/yttwthmode#22]
Had this issue since last month. Tried with Google Chrome and Firefox. Any idea how to fix this?

![Screenshot 2023-12-01 144607](https://github.com/maquinas07/yttwthmode/assets/83646661/62270fd1-ee43-4821-a807-aeb61c63ebe1)

**Comment by maquinas07** [comment]
How can I get to that layout? If I can reproduce it I'll see what I can do.

**Comment by quanpro198** [comment]
I honestly don't know how to reproduce it. I was using it normally then one day it just became like this.

**Comment by maquinas07** [comment]
What's the setup? I see in the screenshot that you're using the mini browser and the chat appears to be in a different monitor.

**Comment by quanpro198** [comment]
The chat is in the same monitor. It's look a bit weird there because i was in fullscreen mode with F11. I took another screenshot without one.

![Screenshot 2023-12-02 211740](https://github.com/maquinas07/yttwthmode/assets/83646661/69bbdd77-f4f7-4e2a-b466-31b5cecdee3c)

Here is a screenshot when i tried to change the chat position to the left:

![Screenshot 2023-12-02 212329](https://github.com/maquinas07/yttwthmode/assets/83646661/353e9dda-6456-40fe-a42b-c33477d0ad60)

As you can see when i enter the theatre mode there is always a black zone at the right side of the browser.

**Comment by maquinas07** [comment]
Can you try the branch from https://github.com/maquinas07/yttwthmode/pull/23 to see if it fixes those errors?

**Comment by quanpro198** [comment]
I tried the new branch. The issue still remains. The only difference is the stream window doesn't resize so now the chat takes up a part of the stream. 

![Screenshot 2023-12-02 222139](https://github.com/maquinas07/yttwthmode/assets/83646661/5258cf5d-265a-452b-904b-059098cb543d)

Also i received these errors. Don't know if it matter or not.

![Screenshot 2023-12-02 222646](https://github.com/maquinas07/yttwthmode/assets/83646661/b54fc941-c983-45c5-b590-b2dfa41683df)

**Comment by maquinas07** [comment]
It could be important actually, I don't get any of those querySelector errors. What's the null variable?

**Comment by quanpro198** [comment]
Here is what it said:  dist/content-script.js:1

I tried to install the extension with a fresh profile in the same browser and it works properly. Then i swith back to this profile and disabled all my other extensions beside this and the issue still remains. Any idea what could have cause it?

**Comment by maquinas07** [comment]
Well, a different person had a similar layout issue and solved it by deleting the cookies, https://github.com/maquinas07/yttwthmode/issues/21. I don't know what could cause this.

**Comment by maquinas07** [comment]
There is a bug in the layout I see now that will get fixed with the branch I linked you to, but your problem is not the same one I'm seeing.

**Comment by quanpro198** [comment]
Clearing cookies doesn't fix it for me unfortunately. Weird because it only happen with this profile specifically.

**Comment by maquinas07** [comment]
And can you see any HTML element occupying that part of the screen?

**Comment by quanpro198** [comment]
Can't see any HTML element when i tried to inspect it. 

So i did some experement and not even my chrome profile that having this issue it is actually my youtube account specifically. Haha this is so weird.

**Comment by maquinas07** [comment]
Could it be the language settings? I imagine that the layout could change drastically with right-to-left languages.
